### ISSUE TITLE
[Feature request] Add the ability to hide the inline code in both preview and reading mode

### ISSUE THREAD

**Issue by Bloe1901** [GRA0007/obsidian-css-inlay-colors#12]
Hi, thank you for such a nice plugin! I would really appreciate it if you can add the ability to hide the inline code so it would only display the color. It will be really helpful in things such as palette building for me! Thanks !

**Comment by GRA0007** [comment]
Ooh interesting suggestion, thanks!

**Comment by GRA0007** [comment]
Thanks for the idea @Bloe1901, I've added this as a setting in v1.2.0, give it a go and let me know if it's what you were expecting!

**Comment by Bloe1901** [comment]
OMGGGG!!!! ❤️❤️THANK YOU SO MUCH!!!! This is so fast too! Now I can make beautiful interactive map and graph! 
![image](https://github.com/user-attachments/assets/8ef3846f-2a53-48a7-804a-46e6a9868137)
Your plugin has allowed me to make stuff like this! Truly grateful<3 🙏
